//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchTable
    {
        public int Branch_ID { get; set; }
        public string Branch_Name { get; set; }
        public string Branch_Adress { get; set; }
        public string Location { get; set; }
    }
}
