//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarListTable
    {
        public int Car_ID { get; set; }
        public int Car_Type_ID { get; set; }
        public string Kilometer { get; set; }
        public string Picture { get; set; }
        public int Undamaged { get; set; }
        public int Available { get; set; }
        public string Car_number { get; set; }
        public int Branch_ID { get; set; }
    }
}
