//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarTypeTable
    {
        public int Car_Type_ID { get; set; }
        public string Manufactor_Name { get; set; }
        public string Model { get; set; }
        public int Price_PerDay { get; set; }
        public int Price_Delay { get; set; }
        public string Production_Year { get; set; }
        public string Gear { get; set; }
    }
}
