//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRental
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YRentalDBEntities : DbContext
    {
        public YRentalDBEntities()
            : base("name=YRentalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BranchTable> BranchTables { get; set; }
        public virtual DbSet<CarListTable> CarListTables { get; set; }
        public virtual DbSet<CarTypeTable> CarTypeTables { get; set; }
        public virtual DbSet<OrdersTable> OrdersTables { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserTable> UserTables { get; set; }
    }
}
